version: "3.3"
services:
  spark-master:
    image: anton31kah/spark-master:3.0.0
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ../../spark-apps:/opt/spark-apps
      - ../../spark-data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_PUBLIC_DNS=${host}
    networks:
      - xmlyelpsparkcluster
  spark-worker-1:
    image: anton31kah/spark-worker:3.0.0
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
#      - SPARK_EXECUTOR_MEMORY=256m
      - SPARK_EXECUTOR_MEMORY=512m
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_PUBLIC_DNS=${host}
    volumes:
      - ../../spark-apps:/opt/spark-apps
      - ../../spark-data:/opt/spark-data
    networks:
      - xmlyelpsparkcluster
  spark-worker-2:
    image: anton31kah/spark-worker:3.0.0
    ports:
      - "8082:8082"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      #      - SPARK_EXECUTOR_MEMORY=256m
      - SPARK_EXECUTOR_MEMORY=512m
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_PUBLIC_DNS=${host}
    volumes:
      - ../../spark-apps:/opt/spark-apps
      - ../../spark-data:/opt/spark-data
    networks:
      - xmlyelpsparkcluster

networks:
  xmlyelpsparkcluster:
