package preprocessing.models.preprocessed

case class User(user_id: String,
                name: String,
                review_count: Double,
                yelping_since: String,
                useful: Double,
                funny: Double,
                cool: Double,
                elite: String,
                friends: String,
                fans: Double,
                average_stars: Double,
                compliment_hot: Double,
                compliment_more: Double,
                compliment_profile: Double,
                compliment_cute: Double,
                compliment_list: Double,
                compliment_note: Double,
                compliment_plain: Double,
                compliment_cool: Double,
                compliment_funny: Double,
                compliment_writer: Double,
                compliment_photos: Double)
